const categories = [
  [
    "Accordion",
    "Bento menu",
    "Breadcrumb",
    "Button",
    "Card",
    "Carousel",
    "Checkbox",
    "Comment box",
    "Dropdown menu",
    "User feed",
    "Form",
    "Hamburger menu",
    "Loader",
    "Modal",
    "Pagination",
    "Picker",
    "Progress bar",
    "Search field",
    "Landing page",
    "Tab bar",
    "Toggle switch",
  ],

  [
    "Neubrutalism",
    "Glassmorphism",
    "Art Deco",
    "Art Nouveau",
    "Retro",
    "Pop Art",
    "Bauhaus",
    "90s",
    "Minimalist",
    "Renaissance",
    "Romanticism",
    "Surrealism",
  ],

  [
    "Teacher",
    "Physician",
    "Engineer",
    "Architect",
    "Chef",
    "Veterinarian",
    "Scientist",
    "Lawyer",
    "Artist",
    "Pharmacist",
    "Secretary",
    "Graphic Designer",
    "Journalist",
    "Software Developer",
    "Businessperson",
    "Actor",
    "Hairdresser",
    "Librarian",
    "Gardener",
    "Tailor",
    "Bakery owner",
    "Photographer",
    "Estate agent",
    "Bar owner",
    "Fashion designer",
  ],
];

export default categories;